name: Preview docs on github 

on:
  pull_request:
    branches:
      - "dev-517"
    paths:
      - docs/**

jobs:
  preview:
    uses: apollographql/docs/.github/workflows/preview.yml@main
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
